### ISSUE TITLE
echarts-2.0.0, zrender-2.0.7

### ISSUE THREAD

**Issue by hail812** [ecomfe/echarts-optimizer#12]
# 这个 WARN 啥意思，有什么影响呢
![echarts-optimize](http://hailog.com/upload/e.jpg)

**Comment by otakustay** [comment]
> Dropping unreachable code

有些代码编译器分析为永远不可能被执行，所以删了

> Dropping unused function argument

函数的某个参数根据函数体的分析不可能被用到，所以删了

> Dropping unused variable

某个非全局的变量根据分析不可能被用到，所以删了

经常的事，无视就好
