### ISSUE TITLE
仅选用部分图表类型，编译后丢失函数

### ISSUE THREAD

**Issue by cuiguojie** [ecomfe/echarts-optimizer#13]
图表配置文件如下
```
exports.modules = {
    main: {name: 'echarts/echarts'},
    parts: [
        {name: 'echarts/chart/line', weight: 100},
        {name: 'echarts/chart/bar', weight: 100},
        {name: 'echarts/chart/pie', weight: 90},
        {name: 'echarts/chart/radar', weight: 30}
    ]
};
```

编译后的文件，网页端点击图表会提示14892行错误，查看源码，缺少了```Base.prototype.getTansform```这个函数。

补充：供编译的源文件版本为echarts 2.2.0和zrender 2.0.7；我用的是script标签直接引入的echarts-all.js

**Comment by pissang** [comment]
如果是自己编译需要保持两个代码仓库的版本同步，zrender 在最新的代码里 `getTransform` 方法已经改为 `transformCoordToLocal` 方法，如果 `echarts` 没有同步到最新版本就会报这个错

**Comment by cuiguojie** [comment]
分别下载的http://echarts.baidu.com/build/echarts-2.2.0.zip和https://codeload.github.com/ecomfe/zrender/zip/master，然后看zrender代码里写的是2.0.7，跟echarts里的版本号一致啊。

不过我自己添加了```getTansform```函数进去解决了

**Comment by pissang** [comment]
master 的是最新的代码，echarts 也需要下载 master 分支的，或者 zrender 下载 [最新 release 的包](https://github.com/ecomfe/zrender/releases) 因为没有发布新版本所以代码里的版本号还是 2.0.7
