### ISSUE TITLE
npm install -g echarts-optimizer 一直安装失败

### ISSUE THREAD

**Issue by qqf611** [ecomfe/echarts-optimizer#14]
![image](https://cloud.githubusercontent.com/assets/10704262/6723977/f0cf42a0-ce2a-11e4-801f-915273ca8d7d.png)

这个问题应该怎么解决呢？

**Comment by errorrik** [comment]
registry.npmjs.orp是啥东西，自己配的registry？

看看你的npmrc文件有没有类似下面的行，如果有的话，删掉

```
registry = http://xxx.xx.xx/
```
