### ISSUE TITLE
压缩echarts时候，可以不把esl打包进去么？

### ISSUE THREAD

**Issue by struggling-bird** [ecomfe/echarts-optimizer#17]
我想用其它的amd引擎，但是好像打包自动就打进去esl了，不知道有没有办法屏蔽这个呢？

**Comment by errorrik** [comment]
optimizer没有做这个定制功能。因为大多数用户并没有用amd的方式开发，我们期望大家能够通过一个script，就能引入echarts，也能获得amd提供的按需加载。

但是，没关系。我猜你用的是requirejs。esl的规则是，如果页面上已经存在amd环境，就不创建自己的环境，用当前的。所以，你只要先引用requirejs，页面上就是requirejs，不是esl。

当然，你会多了3kb。但是echarts这么大的东西你都用了，这点影响应该不大。而且

1. 网速这么快，连接成本大于传输成本
1. 大多数时候它会被cache

**Comment by struggling-bird** [comment]
好的，谢谢解答，非常感谢
