### ISSUE TITLE
现在没人用这个了么？我的也出现问题了

### ISSUE THREAD

**Issue by SynChron1zed** [ecomfe/echarts-optimizer#19]
![image](https://cloud.githubusercontent.com/assets/18717051/23846696/93eddca2-0809-11e7-9c91-03898da5cc02.png)
![image](https://cloud.githubusercontent.com/assets/18717051/23846709/a3259af2-0809-11e7-9a18-4b3715559624.png)

**Comment by SynChron1zed** [comment]
目录应该没有问题吧

**Comment by pissang** [comment]
新版本的 echarts 是用 webpack 构建的

**Comment by SynChron1zed** [comment]
@pissang  意思就是说玩不了了？

**Comment by SynChron1zed** [comment]
echarts tooltip 的轮播搞过么

**Comment by fooller** [comment]
我也出现了 这个问题 我不知道为什么

**Comment by SynChron1zed** [comment]
@fooller  我记得这个问题 应该重新npm吧 我忘了怎么解决的咯
