### ISSUE TITLE
仍然无法构建

### ISSUE THREAD

**Issue by echoloyuk** [ecomfe/echarts-optimizer#7]
按照readme的说明，执行了echarts-optimize，报错，无法构建。这个问题是什么原因引起的？
````
D:\Works\SVN\tui\trunk\code\HtmlDemo\resources\echarts>echarts-optimize

D:\Works\SVN\tui\trunk\code\HtmlDemo\resources\echarts\node_modules\echarts-optimizer\index.js:124
        result += analyse.getAnalysed(mod).builtCode;
                                          ^
TypeError: Cannot read property 'builtCode' of undefined
    at D:\Works\SVN\tui\trunk\code\HtmlDemo\resources\echarts\node_modules\echarts-optimizer\index.js:124:43
    at Array.forEach (native)
    at Object.exports.packAsAll (D:\Works\SVN\tui\trunk\code\HtmlDemo\resources\echarts\node_modules\echarts-optimizer\index.js:123:10)
    at Object.<anonymous> (D:\Works\SVN\tui\trunk\code\HtmlDemo\resources\echarts\node_modules\echarts-optimizer\bin\echarts-optimize:27:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
````

**Comment by echoloyuk** [comment]
```
result += analyse.getAnalysed(mod).builtCode;
```
报错的这段具体是什么原因的呢？目前尝试着将这段修改成：
```
result += analyse.getAnalysed(mod) && analyse.getAnalysed(mod).builtCode;
```
可以构建成功，但是还没有测试构建的结果是否正确。

**Comment by errorrik** [comment]
你是使用了自定义的构建配置么？

**Comment by echoloyuk** [comment]
@errorrik 其实一开始的需求是想构建一个只包含line的charts，因此安装了echarts-optimizer
我是这么安装的：
````
npm install echarts-optimizer -g
````
然后按照readme上的说明，尝试执行一下看看，就报那个错误了。

根目录下有echarts和zrender这两个工程，都是从github上download的。

我后来又换了：
````
npm install echarts-optimizer@0.2.10 -g
````
其他版本，也是这个问题。

还没有添加`echarts-optimize-conf.js`呢

**Comment by huyinghuan** [comment]
同样有这个问题。
![image](https://cloud.githubusercontent.com/assets/3005433/5753877/536bb2ae-9ccb-11e4-9afb-8ec9c92f299e.png)

**Comment by errorrik** [comment]
如果出现这个问题，是不可能构建成功的。就算构建成功了，生成的代码还是会有问题的。产生这个问题的原因只可能是因为echarts或者zrender的源代码不对：

1. 执行目录下不存在echarts或zrender的源码目录。默认是pwd/echarts/src和pwd/zrender/src
2. 源码本身有问题，引用的不是稳定版，或者被改过（我觉得可能性不大）
3. echarts源码版本较新，zrender版本较旧，小于当前echarts所需的最低版本
4. 暂时想不出来了

**Comment by huyinghuan** [comment]
![image](https://cloud.githubusercontent.com/assets/3005433/5754326/538ccbcc-9cd2-11e4-8a50-6fbffaec6f16.png)

**Comment by echoloyuk** [comment]
@errorrik 我感觉2,3这两个问题可能性不大，那就可能是目录的问题。
麻烦给个截图吧~您的echarts和zrender的src下都有什么呢？

我的echarts和zrender是在官网上下载的，解压缩之后，直接改文件名放到执行的目录下的。是不是我的操作有误？

**Comment by echoloyuk** [comment]
哦~果然是zrender的版本不对，master分支不行，换成2.0.6就行了。非常感谢，那看来是自己的问题了。

**Comment by huyinghuan** [comment]
貌似找到了疑似bug的地方了。在修改analyse.js的第362行：
```
exports.getAnalysed = function (id) {
    if (!analysedModules[id]) {
        if(id === "echarts/component/Base"){ //这个if是增加的。貌似是echart这里的命名大小写问题造成的？
            id = "echarts/component/base"
        }
        analyse(id, 1);
    }
```

**Comment by echoloyuk** [comment]
@huyinghuan 你下载zrender的时候，把分支从master改成2.0.6就可以了。没有修改这个代码。之前看到有人提过这个问题，据说master不是最新的，或者别的原因吧。

**Comment by huyinghuan** [comment]
@echoloyuk  没用
![image](https://cloud.githubusercontent.com/assets/3005433/5754763/1b6adb70-9cd8-11e4-9700-3d58d0836c4c.png)

**Comment by echoloyuk** [comment]
@huyinghuan 哦，是嘛？那还是请作者继续关注啊~~反正我是没有你这个问题了。。

**Comment by huyinghuan** [comment]
你说的对，echarts和zrender 都切换到最新tag才可以。

**Comment by errorrik** [comment]
咦，你们是都解决了么，我正打算看看

**Comment by huyinghuan** [comment]
@errorrik  master  分支不能构建， 需要同时切到最新tag才可以.. 例外 想问下 为啥在master分支 我修改了下echarts-optimizer下的个文件又能构建了。上面有提到。

**Comment by errorrik** [comment]
我刚试过是可以的诶。不过我find+grep看了一下，确实echarts有一处require的是`../component/Base`。这是个问题，我去推动改过来。

```
➜  echarts git:(master)  git log
commit 61bc90828e20630015e5f4c4a3c9652fc047b7ce
Author: Kener <kener.linfeng@gmail.com>
Date:   Thu Jan 15 14:28:32 2015 +0800

    add hoverable to K
```

```
➜  zrender git:(master)  git log
commit 5059a8bec81a4660ef56488c72f4edd59a7d478c
Merge: 155fa2b 6f5de3b
Author: linfeng <kener.linfeng@gmail.com>
Date:   Tue Jan 13 18:13:22 2015 +0800

    Merge pull request #111 from beebole/master

    Fix a typo about two console.log
```

**Comment by errorrik** [comment]
已经推动echarts修复，多谢 @huyinghuan 发现一个这么隐蔽而sb的问题
